name: Convert README.ipynb to markdown
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies & Convert README.ipynb
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          jupyter nbconvert --to markdown README.ipynb
      - name: Commit files
        run: |
          git config --local user.email "ajabaja16@gmail.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "Convert README.ipynb to README.md" -a
      - name: Push changes
        if: success()
        uses: ad-m/github-push-action@master
        with:
          branch: main
          github_token: ${{ secrets.ACCESS_TOKEN }}
      - run: jupyter nbconvert --to markdown README.ipynb
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."
